### ISSUE TITLE
Deploy sitewhere-2.0.2 with k8s , while something wrong with sitewhere-mongodb-primary-0

### ISSUE THREAD

**Issue by GanKanTechnology** [sitewhere/sitewhere-k8s#21]
**Describe the bug**
As the topic ,the pod  sitewhere-mongodb-primary-0 kept restarting over and over as well as sitewhere-mongodb-secondary-0, they "CrashLoopBackOff" . Other containers all running and ready.

**Provide Information**
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
Output of `helm ls sitewhere`
```
NAME     	REVISION	UPDATED                 	STATUS  	CHART          	APP VERSION	NAMESPACE
sitewhere	1       	Mon Jan 21 20:43:47 2019	DEPLOYED	sitewhere-0.1.3	2.0.2      	default  
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): `kubeadm`

### **kubectl logs sitewhere-mongodb-primary-0**  
```
Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues

nami    INFO  Initializing mongodb
mongodb INFO  ==> Deploying MongoDB from scratch...
mongodb INFO  ==> No injected configuration files found. Creating default config files...
Error executing 'postInstallation': If you defined an username you must define a password and a database too
```

### **kubectl describe pod sitewhere-mongodb-primary-0**  
```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  19m                   default-scheduler  Successfully assigned default/sitewhere-mongodb-primary-0 to worker2
  Normal   Pulled     17m (x4 over 18m)     kubelet, worker2   Successfully pulled image "docker.io/bitnami/mongodb:4.0.3"
  Normal   Created    17m (x4 over 18m)     kubelet, worker2   Created container
  Normal   Started    17m (x4 over 18m)     kubelet, worker2   Started container
  Normal   Pulling    14m (x6 over 19m)     kubelet, worker2   pulling image "docker.io/bitnami/mongodb:4.0.3"
  Warning  BackOff    4m32s (x62 over 18m)  kubelet, worker2   Back-off restarting failed container
```

### **kubectl logs sitewhere-mongodb-secondary-0**  
```
Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
nami    INFO  Initializing mongodb
mongodb INFO  ==> Deploying MongoDB from scratch...
mongodb INFO  ==> No injected configuration files found. Creating default config files...
mongodb INFO  ==> Configuring MongoDB replica set
mongodb INFO  ==> Enabling MongoDB replica set name
mongodb INFO  ==> Configuring MongoDB secondary node
mongodb INFO  Trying to connect to MongoDB server
mongodb INFO  Found MongoDB server listening at sitewhere-mongodb:27017
mongodb INFO  MongoDB server listening and working at sitewhere-mongodb:27017
Error executing 'postInstallation': Unable to confirm that sitewhere-mongodb-secondary-0.sitewhere-mongodb-headless.default.svc.cluster.local has been added to the replica set
```
 ### **kubectl describe pod sitewhere-mongodb-secondary-0**
```
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  21m   default-scheduler  Successfully assigned default/sitewhere-mongodb-secondary-0 to worker3
  Warning  Unhealthy  19m   kubelet, worker3   Readiness probe failed: MongoDB shell version v4.0.3
connecting to: mongodb://127.0.0.1:27017
2019-01-21T12:45:26.245+0000 E QUERY    [js] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:257:13
@(connect):1:6
exception: connect failed
  Warning  Unhealthy  12m  kubelet, worker3  Readiness probe failed: MongoDB shell version v4.0.3
connecting to: mongodb://127.0.0.1:27017
2019-01-21T12:52:16.239+0000 E QUERY    [js] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:257:13
@(connect):1:6
exception: connect failed
  Normal   Pulling  10m (x4 over 21m)   kubelet, worker3  pulling image "docker.io/bitnami/mongodb:4.0.3"
  Normal   Pulled   10m (x4 over 19m)   kubelet, worker3  Successfully pulled image "docker.io/bitnami/mongodb:4.0.3"
  Normal   Created  10m (x4 over 19m)   kubelet, worker3  Created container
  Normal   Started  10m (x4 over 19m)   kubelet, worker3  Started container
  Warning  BackOff  60s (x12 over 11m)  kubelet, worker3  Back-off restarting failed container
```

seems that  "If you defined an username you must define a password and a database too" , I'm not quite sure what's the username? How should I deploy sitewhere-2.0.2 wiht sitewhere-k8s-0.1.3 successfully please ?

**Comment by jorgevillaverde-sitewhere** [comment]
Hi @GanKanTechnology,

This error seems to be related to this [issue](https://github.com/helm/charts/issues/10539) with MongoDB.
Do you get this error every time to deploy?

You should be able to deploy with

```console
helm repo add sitewhere https://sitewhere.io/helm-charts
helm repo update
helm install --name sitewhere sitewhere/sitewhere
```

If you are running with low resources, you could try [sitewhere-k8s-0.1.4](https://github.com/sitewhere/sitewhere-k8s/tree/sitewhere-k8s-0.1.4) branch and deploy with

```console
helm install --name sitewhere \
  -f ./sitewhere/dev-values.yaml \
  sitewhere
```

**Comment by GanKanTechnology** [comment]
Hi~ @jorgevillaverde-sitewhere  thanks for your help , but still the same question.

My steps followed what you've wrote:
      helm repo add sitewhere https://sitewhere.io/helm-charts
      helm repo update
      helm install --name sitewhere sitewhere/sitewhere ( Yes, this time I didn't git clone sitewhere-k8s to my local server )

Still the same problem with pod sitewhere-mongodb-primary, "CrashLoopBackOff "
when "**kubectl logs sitewhere-mongodb-primary-0** " , logs as followed : 
     Welcome to the Bitnami mongodb container
     Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
     Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
     nami    INFO  Initializing mongodb
     mongodb INFO  ==> Deploying MongoDB from scratch...
     mongodb INFO  ==> No injected configuration files found. Creating default config files...
     Error executing 'postInstallation': If you defined an username you must define a password and a           
     database too.

BUT, in the issue you've mentioned (https://github.com/helm/charts/issues/10539), I did run the following command as the issue told: 
      **helm install --name my-release stable/mongodb --set replicaSet.enabled=true**
It seems right. And all the mongodbs as followed:

**#kubectl get pods | grep mongodb**
my-release-mongodb-arbiter-0                     1/1     Running            0          28s
my-release-mongodb-primary-0                     1/1     Running            0          28s
my-release-mongodb-secondary-0                   1/1     Running            0          28s
sitewhere-mongodb-arbiter-0                      0/1     CrashLoopBackOff   8          41m
sitewhere-mongodb-primary-0                      0/1     CrashLoopBackOff   12         41m
sitewhere-mongodb-secondary-0                    0/1     CrashLoopBackOff   12         41m   

With some other info maybe useful:
**# helm list**
NAME      	REVISION	UPDATED                 	STATUS  	CHART          	APP VERSION	NAMESPACE
my-release	1       	Wed Jan 23 15:09:30 2019	DEPLOYED	mongodb-5.2.0  	4.0.3      	default  
sitewhere 	1       	Wed Jan 23 14:28:46 2019	DEPLOYED	sitewhere-0.1.3	2.0.2      	default 

In that issue  they upgraded the stable/mongodb  chart  version  to  5.1.1 , did our sitewhere chart update too? To prove this ,I executed "helm fetch sitewhere/sitewhere" and got "sitewhere-0.1.3.tgz"，
untar it , and found the value below:

./sitewhere/charts/sitewhere-infra-database/charts/mongodb/Chart.yaml:version: 5.0.1
./sitewhere/charts/sitewhere-infra-database/requirements.yaml:  version: 5.0.1
./sitewhere/charts/sitewhere-infra-database/requirements.lock:  version: 5.0.1

I change all these "5.0.1" to "5.2.0" , and run "helm dependency update" , and  helm purged all the pods 
 and delete all the pvcs. Then run 
       helm install --name sitewhere ./sitewhere  [this time I use the local files that I've changed the version values ]

But it still didn't work, and still the same error:
   Error executing 'postInstallation': If you defined an username you must define a password and a database too.

Did we really define an username somewhere without a password or database ? If we did , is it necessary to define the username ?

I don't know what to do now. Do you have any opinion please ?

**Comment by jorgevillaverde-sitewhere** [comment]
Hi @GanKanTechnology, 

 >Did we really define an username somewhere without a password or database ? If we did , is it necessary to define the username ?

No, we are not. Actually this is what we override from `stable/mongodb` chart

```yaml
mongodb:
  usePassword: false
  replicaSet:
    enabled: true
    replicas:
      secondary: 1
      arbiter: 1
  persistence:
    storageClass: rook-ceph-block
    accessModes:
      - ReadWriteOnce
    storage: 10Gi
```
You can take a look [here](https://github.com/sitewhere/sitewhere-k8s/blob/master/charts/sitewhere-infra-database/values.yaml).

**Comment by jorgevillaverde-sitewhere** [comment]
What are the resources of your Kubernetes cluster? I have face a similar situation when running low of resources. If that's the case, let me know and I can point you on running sitewhere with minimal resources. I keep digging to find a solution to this issue.

**Comment by GanKanTechnology** [comment]
> What are the resources of your Kubernetes cluster? I have face a similar situation when running low of resources. If that's the case, let me know and I can point you on running sitewhere with minimal resources. I keep digging to find a solution to this issue.

Regarding resources of  Kubernetes cluster ,do you mean hardware resources? I had  6 servers provided by a cloud service provider .Three masters & three workers, all masters tainted with no working pods allocated. All these servers used only for k8s-cluster & sitewhere. 

1. All have the same CPU as followed:   #lscpu
          Architecture:          x86_64
          CPU op-mode(s):        32-bit, 64-bit
          Byte Order:            Little Endian
          CPU(s):                8
          On-line CPU(s) list:   0-7
          Thread(s) per core:    1
          Core(s) per socket:    8
          Socket(s):             1
          NUMA node(s):          1
          Vendor ID:             GenuineIntel
          CPU family:            6
          Model:                 63
          Model name:            Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
          Stepping:              2
          CPU MHz:               2494.567
          BogoMIPS:              4988.58
          Hypervisor vendor:     Xen
          Virtualization type:   full
          L1d cache:             32K
          L1i cache:             32K
          L2 cache:              256K
          L3 cache:              30720K
          NUMA node0 CPU(s):     0-7

2、memory info :  each 16G.
3、Storage: got this info from rook-ceph-tools:
         sh-4.2# ceph status
  cluster:
    id:     d5824b79-5fa8-4c33-b2ad-289843c4eabe
    health: HEALTH_OK 
  services:
    mon: 3 daemons, quorum a,c,b
    mgr: a(active)
    osd: 3 osds: 3 up, 3 in
   data:
    pools:   1 pools, 100 pgs
    objects: 274  objects, 405 MiB
    usage:   23 GiB used, 5.8 TiB / 5.9 TiB avail
    pgs:     100 active+clean

**Comment by derekadams** [comment]
Thanks for providing the information. That server configuration should have no problem running all of the SiteWhere components with plenty of room to scale the system as needed. We will continue to try to isolate the issue.

**Comment by GanKanTechnology** [comment]
> Thanks for providing the information. That server configuration should have no problem running all of the SiteWhere components with plenty of room to scale the system as needed. We will continue to try to isolate the issue.

Thanks a lot. I found that in the /sitewhere-infra-database/requirements.yaml the version is now 5.0.1. Is this maybe the reason?

**Comment by derekadams** [comment]
That may very well be the case. I will update the dependency to `5.2.0` for the upcoming `0.1.4` chart release. We are also trying to get the new HTTP outbound connector (sitewhere/sitewhere#685) included in the `sitewhere-2.0.3` images before we release the new chart. If all goes well, we can release both tomorrow.

**Comment by jorgevillaverde-sitewhere** [comment]
Hi @GanKanTechnology, I can't reproduce the issue, but taking a closer look, I see that the pods from MongoDB stay in the `CrashLoopBackOff` state. This could be due to pod not being able to start in time. Take a look at livenessProbe and redinessProbe values of [mongodb](https://github.com/helm/charts/blob/6340adbd3b93f2a9d9b7f5b48efd26f5a5a80ab7/stable/mongodb/templates/statefulset-primary-rs.yaml#L148).

This are the values by default

```yaml
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
``` 
Could you increase some of the values to see if mongodb pod starts correctly. 
For example, add

```
--set sitewhere-infra-database.mongodb.readinessProbe.timeoutSeconds=20
```
to your `helm install` command

**Comment by GanKanTechnology** [comment]
Hi  @derekadams @jorgevillaverde-sitewhere ,

With the latest chart files and sitewhere images, I deployed  the sitewhere-k8s  without obvious error.

**Thanks a lot for your work to both of you!**

But when trying to connect the sitewhere-service with admin-ui, I found that it's not very fluent or stable.

At first it cann't be connected after deploying about 20 minitues, with the error hint "Request failed with status code 500". 
After about half an hour (during that time I was reading logs of each pod),  the connection was able to be established. Hmm. Then I logged in, found that not much  information in the "Default Tenant" , no customers, no devices, only some info in the "assets management" part. I think this may be a bug ,or maybe that you've decided not to show too much infomation. So I created a new tenant and added customers, devices, assets and other infomation. Till now it seems running well. Later we'll go on to do more test and let you know. Thanks again.

**Comment by derekadams** [comment]
I'm glad to hear the system is at least starting up successfully. Part of the slow startup may be caused by the images pulling from Docker Hub since they were updated to version 2.0.3 in the new chart. It also takes some time for the Zookeeper and Kafka clusters to stabilize in HA mode, but it shouldn't take as long as you are seeing. 

Regarding the lack of information in the default tenant, that must be a bug. The default tenant should automatically populate with sample data that includes most of the device management model. We have seen this bug previously, but thought it was fixed in the 2.0.3 images. When the tenant is created in the model, a Kafka topic should pick up the update and run the initialization scripts to populate the data. Apparently, the update is not being triggered, so the data is not populated. We will research the error and make a fix available as soon as possible. Thanks for your patience!

**Comment by derekadams** [comment]
We have narrowed down the issue to the new HA Kafka settings added in the `0.1.4` Helm chart. We will close this issue and track the Kafka problems here: #23

**Comment by GanKanTechnology** [comment]
Hi @derekadams Thanks for your reply. I noticed that there are sitewhere-2.0.4 version docker images  and sitewhere-k8s-0.1.5 chart files, so I tested again with these two latest version. There's still something not fixed yet. I'll continue to follow up. But please don't be hurry, wish everything goes well on  you all.
Later when you fix the bug I'll test it again and comment in the new issue #23,

**Comment by derekadams** [comment]
Hi @GanKanTechnology , We just created the new branches for the next release, but there is not much new in them yet. In the short term, you can get around the issues by running the developer version of the platform, which only runs a single instance of Kafka/Zookeeper/MongoDB. If you clone the `sitewhere-k8s` repository and run:
```
helm install --name sitewhere -f ./sitewhere/dev-values.yaml sitewhere
```
the system will start with no problems and the construction sample data will be loaded.

**Comment by GanKanTechnology** [comment]
Hi @derekadams , Thank you. I did as you said. Though it didn't  perform as expected,  we don't need to be depressed. Later today I'll try some earlier versions to build a stable running environment to do other tests. 

To make the SiteWhere platform suitable for production environment. there seems still a long way and a lot to do. Just keep on improving. I'll pay attention to this and keep in touch.

Thanks again for your patience.
